version: "3"

services:
  api:
    build:
      context: . # use the current directory
      dockerfile: Dockerfile # use the Dockerfile in the current directory
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build: ./db # use the Dockerfile in the db directory
    ports:
      - "6379:6379"
    volumes:
      - .data:/data

  frontend:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./webpage:/app
    command: sh -c "npm install && npm start"
    ports:
      - "5500:5500"
    depends_on:
      - api
